# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef3c55b26562bd9c970a128c99cd5c2494d75716173ff80dde388ea1e96a730fd0ef05b32879d36ada4e81d095dc1373f8eae1fc46986e8cb2e7396b3eb5577

test:
  secret_key_base: 4e7e235a92ecc15927692e8929453b3d8a5593cb902c6f048439fe264675f1f1aae35c1ca7b5fc3f5cf6d4027c96a6df2640768aa8d1fc6f4f670c0c898f6867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
